### ISSUE TITLE
.css, .js 参照のページ項目について

### ISSUE THREAD

**Issue by mac-araki** [anlp-nenji/nlp2023-md#2]
@hiroshi-matsuda-rit さま
cc: @sorami さま

# 背景

将来的にbootstrapを利用しない形にスタイルを変更したいという意向があり、それを踏まえて現時点で bootstrap や css を参照しているページがどの程度あるか（＝依存しているページがどの程度あるか）リストアップして欲しいというご要望を頂いていた認識です

# 実施内容

./bootstrap/, ./css/ 以下の.css, .jsファイルを参照しているページ項目について調査いたしました

* .css:　殆どのページ項目について.cssにより表示スタイルの調整が行われております
* .js:　サイドメニューのスクロール追従機能を実現しております。このため、利用を無効化するとサイドメニューがページ左上に固定されます

並行して、簡易にスタイルを調整出来ないかテンプレートをざっと洗ってみましたが、ここからのスタイル変更はかなりの労力を必要とする印象でした

今回の調査はここまでにとどめ、.css, .jsを利用しない更なる近代化については、ページデザインの大幅変更を行う際に改めて検討される形がよろしいかと思いますがいかがでしょうか？

**Comment by sorami** [comment]
調査ありがとうございます！

> 今回の調査はここまでにとどめ、.css, .jsを利用しない更なる近代化については、ページデザインの大幅変更を行う際に改めて検討される形がよろしいかと思いますがいかがでしょうか？
おっしゃるように、これ以上はこの段階では難しいかなと考えます。ですので、一旦このissueはこれにてcloseさせていただければと思います。

改めて、ありがとうございました！
